import type {
  GovernmentScheme,
  Complaint,
  DemoPersona,
  CivicJourneyEvent,
  DashboardStats,
  AdminMetrics,
} from './types';

export const SCHEMES: GovernmentScheme[] = [
  {
    id: 'pmsss',
    name: 'Post Matric Scholarship for SC/ST Students',
    nameHi: 'एससी/एसटी छात्रों के लिए पोस्ट मैट्रिक छात्रवृत्ति',
    category: 'education',
    department: 'Ministry of Social Justice and Empowerment',
    shortDescription: 'Financial assistance for SC/ST students pursuing post-matriculation studies.',
    description:
      'The Post Matric Scholarship Scheme provides financial assistance to students belonging to Scheduled Castes and Scheduled Tribes for pursuing post-matriculation courses in recognized institutions. The scholarship covers tuition fees, maintenance allowance, and other educational expenses.',
    eligibility: [
      { id: 'e1', label: 'Caste', description: 'Must belong to SC or ST category', field: 'caste', operator: 'in', value: ['SC', 'ST'] },
      { id: 'e2', label: 'Income', description: 'Family income should not exceed ₹2.5 lakh per annum', field: 'income', operator: 'lte', value: 250000 },
      { id: 'e3', label: 'Education', description: 'Must have passed matriculation (Class 10)', field: 'education', operator: 'gte', value: 10 },
      { id: 'e4', label: 'Enrollment', description: 'Must be enrolled in a recognized post-matric course', field: 'isStudent', operator: 'bool', value: true },
    ],
    eligibilitySummary: 'SC/ST students with family income up to ₹2.5 lakh/year, enrolled in post-matric courses.',
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Mark sheet of last examination', 'Bank passbook copy', 'Aadhaar Card', 'Institution admission proof'],
    applicationProcess: [
      'Register on the National Scholarship Portal (scholarships.gov.in)',
      'Fill in personal and academic details',
      'Upload required documents',
      'Submit application and note the application ID',
      'Track application status on the portal',
    ],
    officialSource: 'National Scholarship Portal',
    sourceUrl: 'https://scholarships.gov.in',
    lastVerified: '2025-01-15',
    availability: 'national',
    applicationDeadline: 'October 31 (varies by state)',
    benefits: 'Up to ₹15,000-20,000 per year for maintenance + full tuition fee reimbursement',
    tags: ['scholarship', 'sc', 'st', 'education', 'students'],
  },
  {
    id: 'nsp-merit',
    name: 'National Merit-cum-Means Scholarship',
    nameHi: 'राष्ट्रीय योग्यता-आधारित छात्रवृत्ति',
    category: 'education',
    department: 'Ministry of Education',
    shortDescription: 'Scholarship for economically weaker students with strong academic merit.',
    description:
      'The Merit-cum-Means Scholarship provides financial assistance to economically weaker students from minority communities to pursue professional and technical courses at undergraduate and postgraduate levels.',
    eligibility: [
      { id: 'e1', label: 'Income', description: 'Family income should not exceed ₹3 lakh per annum', field: 'income', operator: 'lte', value: 300000 },
      { id: 'e2', label: 'Academic', description: 'Minimum 50% marks in previous examination', field: 'marks', operator: 'gte', value: 50 },
      { id: 'e3', label: 'Enrollment', description: 'Admitted in a professional/technical course', field: 'isStudent', operator: 'bool', value: true },
    ],
    eligibilitySummary: 'Minority community students with family income up to ₹3 lakh/year and 50%+ marks.',
    requiredDocuments: ['Income Certificate', 'Mark sheet', 'Minority Community Certificate', 'Bank passbook', 'Aadhaar Card', 'Institution fee receipt'],
    applicationProcess: [
      'Visit National Scholarship Portal (scholarships.gov.in)',
      'Create an account with Aadhaar',
      'Select Merit-cum-Means Scholarship',
      'Fill academic and income details',
      'Upload documents and submit',
    ],
    officialSource: 'National Scholarship Portal',
    sourceUrl: 'https://scholarships.gov.in',
    lastVerified: '2025-02-01',
    availability: 'national',
    applicationDeadline: 'September 30',
    benefits: '₹20,000 per year (₹1,000/month for 10 months) + course fee reimbursement up to ₹20,000',
    tags: ['scholarship', 'minority', 'merit', 'education', 'students'],
  },
  {
    id: 'pm-kisan',
    name: 'PM-KISAN Samman Nidhi',
    nameHi: 'प्रधानमंत्री किसान सम्मान निधि',
    category: 'agriculture',
    department: 'Ministry of Agriculture and Farmers Welfare',
    shortDescription: '₹6,000 per year income support to small and marginal farmers.',
    description:
      'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN) provides income support of ₹6,000 per year to all landholding farmer families in three equal installments, to supplement their financial needs for procuring agricultural inputs and other needs.',
    eligibility: [
      { id: 'e1', label: 'Farmer', description: 'Must be a landholding farmer', field: 'isFarmer', operator: 'bool', value: true },
      { id: 'e2', label: 'Exclusion', description: 'Not applicable to institutional farmers, income tax payers, or government employees', field: 'income', operator: 'lt', value: 10000000 },
    ],
    eligibilitySummary: 'All landholding farmer families. Excludes income-tax payers and government employees.',
    requiredDocuments: ['Aadhaar Card', 'Land ownership documents (Khata/Khatauni)', 'Bank account details', 'Mobile number'],
    applicationProcess: [
      'Visit pmkisan.gov.in or visit nearest Common Service Centre (CSC)',
      'Enter Aadhaar number and verify OTP',
      'Fill in land details and bank account information',
      'Submit at CSC or online',
      'Benefit is transferred directly to bank account in 3 installments',
    ],
    officialSource: 'PM-KISAN Portal',
    sourceUrl: 'https://pmkisan.gov.in',
    lastVerified: '2025-01-20',
    availability: 'national',
    benefits: '₹6,000 per year in 3 equal installments of ₹2,000 each',
    tags: ['farmer', 'agriculture', 'income support', 'subsidy'],
  },
  {
    id: 'pmfby',
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    nameHi: 'प्रधानमंत्री फसल बीमा योजना',
    category: 'agriculture',
    department: 'Ministry of Agriculture and Farmers Welfare',
    shortDescription: 'Crop insurance against natural calamities, pests, and diseases.',
    description:
      'PMFBY provides comprehensive crop insurance coverage against natural calamities, pests, and diseases to farmers. It aims to stabilize farmers\' income and encourage them to adopt innovative agricultural practices.',
    eligibility: [
      { id: 'e1', label: 'Farmer', description: 'All farmers including tenant farmers and sharecroppers', field: 'isFarmer', operator: 'bool', value: true },
      { id: 'e2', label: 'Loan', description: 'Loanee farmers are covered compulsorily; others voluntary', field: 'isFarmer', operator: 'bool', value: true },
    ],
    eligibilitySummary: 'All farmers (loanee and non-loanee), tenant farmers, and sharecroppers growing notified crops.',
    requiredDocuments: ['Aadhaar Card', 'Land documents or tenancy certificate', 'Bank account details', 'Sowing certificate from local agriculture officer'],
    applicationProcess: [
      'Contact your bank or nearest agriculture office',
      'Fill the PMFBY application form',
      'Submit land/tenancy documents',
      'Pay premium (1.5% for Rabi, 2% for Kharif, 5% for commercial/horticulture crops)',
      'Insurance is linked to your bank account',
    ],
    officialSource: 'PMFBY Portal',
    sourceUrl: 'https://pmfby.gov.in',
    lastVerified: '2025-01-10',
    availability: 'national',
    benefits: 'Full sum insured against crop loss due to natural calamities, pests, and diseases',
    tags: ['farmer', 'insurance', 'agriculture', 'crop'],
  },
  {
    id: 'old-age-pension',
    name: 'Indira Gandhi National Old Age Pension Scheme (IGNOAPS)',
    nameHi: 'इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन योजना',
    category: 'pension',
    department: 'Ministry of Rural Development',
    shortDescription: 'Monthly pension for BPL senior citizens aged 60 and above.',
    description:
      'IGNOAPS provides a monthly pension to persons aged 60 years and above belonging to Below Poverty Line (BPL) households. The central government provides ₹200/month (₹500 for 80+), and states may add additional amounts.',
    eligibility: [
      { id: 'e1', label: 'Age', description: 'Must be 60 years or above', field: 'age', operator: 'gte', value: 60 },
      { id: 'e2', label: 'BPL', description: 'Must belong to a BPL household', field: 'bpl', operator: 'bool', value: true },
    ],
    eligibilitySummary: 'BPL senior citizens aged 60+. ₹200/month (60-79), ₹500/month (80+).',
    requiredDocuments: ['Aadhaar Card', 'Age proof (Voter ID, Birth Certificate)', 'BPL Certificate', 'Bank passbook', 'Residence proof'],
    applicationProcess: [
      'Visit your Gram Panchayat / Municipality office',
      'Fill the IGNOAPS application form',
      'Attach age proof, BPL certificate, and bank details',
      'Submit to the concerned officer',
      'Pension is credited directly to bank account',
    ],
    officialSource: 'NSAP Portal',
    sourceUrl: 'https://nsap.nic.in',
    lastVerified: '2025-01-05',
    availability: 'national',
    benefits: '₹200/month (age 60-79), ₹500/month (age 80+) + state top-up',
    tags: ['pension', 'senior citizen', 'bpl', 'welfare'],
  },
  {
    id: 'pmjay',
    name: 'Ayushman Bharat (PM-JAY)',
    nameHi: 'आयुष्मान भारत (पीएम-जय)',
    category: 'health',
    department: 'Ministry of Health and Family Welfare',
    shortDescription: '₹5 lakh health insurance cover per family per year — cashless treatment.',
    description:
      'Pradhan Mantri Jan Arogya Yojana (PM-JAY) provides a health cover of ₹5 lakh per family per year for secondary and tertiary hospitalization. It is completely cashless and paperless at empaneled hospitals across India.',
    eligibility: [
      { id: 'e1', label: 'SECC', description: 'Eligible families as per SECC 2011 database', field: 'secc', operator: 'bool', value: true },
      { id: 'e2', label: 'Category', description: 'Covers poor and vulnerable families', field: 'bpl', operator: 'bool', value: true },
    ],
    eligibilitySummary: 'Poor and vulnerable families identified through SECC 2011. Check eligibility at pmjay.gov.in using mobile number.',
    requiredDocuments: ['Aadhaar Card', 'Mobile number (linked to Aadhaar)', 'Ration Card (optional)'],
    applicationProcess: [
      'Visit pmjay.gov.in or call 14555',
      'Enter your mobile number to check eligibility',
      'If eligible, visit nearest Ayushman Bharat center (CSC/A hospital)',
      'Get your Ayushman Card (e-card) made',
      'Use e-card at any empaneled hospital for cashless treatment',
    ],
    officialSource: 'PM-JAY Portal',
    sourceUrl: 'https://pmjay.gov.in',
    lastVerified: '2025-02-10',
    availability: 'national',
    benefits: '₹5 lakh per family per year — cashless hospitalization at empaneled hospitals',
    tags: ['health', 'insurance', 'free treatment', 'welfare', 'bpl'],
  },
  {
    id: 'pmjjby',
    name: 'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)',
    nameHi: 'प्रधानमंत्री जीवन ज्योति बीमा योजना',
    category: 'finance',
    department: 'Ministry of Finance',
    shortDescription: '₹2 lakh life insurance cover for just ₹436/year.',
    description:
      'PMJJBY is a life insurance scheme offering a death cover of ₹2 lakh at an annual premium of just ₹436. It is available to all savings bank account holders aged 18-50 years.',
    eligibility: [
      { id: 'e1', label: 'Age', description: '18 to 50 years', field: 'age', operator: 'lte', value: 50 },
      { id: 'e2', label: 'Bank Account', description: 'Must have a savings bank account', field: 'bankAccount', operator: 'bool', value: true },
      { id: 'e3', label: 'Consent', description: 'Auto-debit consent for premium', field: 'autoDebit', operator: 'bool', value: true },
    ],
    eligibilitySummary: 'Savings bank account holders aged 18-50. Premium: ₹436/year. Cover: ₹2 lakh on death.',
    requiredDocuments: ['Aadhaar Card', 'Savings bank account details', 'Nominee details', 'Auto-debit consent form'],
    applicationProcess: [
      'Visit your bank branch or use your bank\'s mobile app',
      'Fill the PMJJBY application form',
      'Submit Aadhaar and nominee details',
      'Give auto-debit consent for ₹436 annual premium',
      'Coverage starts after first premium deduction',
    ],
    officialSource: 'PMJJBY (jansuraksha.gov.in)',
    sourceUrl: 'https://www.jansuraksha.gov.in',
    lastVerified: '2025-01-12',
    availability: 'national',
    benefits: '₹2 lakh life cover on death of the insured, premium ₹436/year',
    tags: ['insurance', 'life', 'finance', 'low cost'],
  },
  {
    id: 'pmsvy',
    name: 'Pradhan Mantri Suraksha Bima Yojana (PMSBY)',
    nameHi: 'प्रधानमंत्री सुरक्षा बीमा योजना',
    category: 'finance',
    department: 'Ministry of Finance',
    shortDescription: 'Accident insurance cover of ₹2 lakh for just ₹20/year.',
    description:
      'PMSBY provides accidental death and disability cover of ₹2 lakh at an annual premium of just ₹20. Available to all savings bank account holders aged 18-70 years.',
    eligibility: [
      { id: 'e1', label: 'Age', description: '18 to 70 years', field: 'age', operator: 'lte', value: 70 },
      { id: 'e2', label: 'Bank Account', description: 'Must have a savings bank account', field: 'bankAccount', operator: 'bool', value: true },
    ],
    eligibilitySummary: 'Savings bank account holders aged 18-70. Premium: ₹20/year. Cover: ₹2 lakh on accidental death/disability.',
    requiredDocuments: ['Aadhaar Card', 'Savings bank account details', 'Nominee details', 'Auto-debit consent form'],
    applicationProcess: [
      'Visit your bank branch or use mobile banking app',
      'Fill the PMSBY application form',
      'Submit Aadhaar and nominee details',
      'Give auto-debit consent for ₹20 annual premium',
      'Coverage starts after premium deduction',
    ],
    officialSource: 'PMSBY (jansuraksha.gov.in)',
    sourceUrl: 'https://www.jansuraksha.gov.in',
    lastVerified: '2025-01-12',
    availability: 'national',
    benefits: '₹2 lakh on accidental death or total disability, ₹1 lakh for partial disability. Premium: ₹20/year',
    tags: ['insurance', 'accident', 'finance', 'low cost'],
  },
  {
    id: 'pmay',
    name: 'Pradhan Mantri Awas Yojana (PMAY)',
    nameHi: 'प्रधानमंत्री आवास योजना',
    category: 'housing',
    department: 'Ministry of Housing and Urban Affairs',
    shortDescription: 'Affordable housing for all — subsidy on home loans.',
    description:
      'PMAY aims to provide affordable housing to all by 2024. It offers interest subsidy on home loans for construction, purchase, or enhancement of houses for economically weaker and low-income groups.',
    eligibility: [
      { id: 'e1', label: 'Income', description: 'Annual family income up to ₹6 lakh (EWS/LIG)', field: 'income', operator: 'lte', value: 600000 },
      { id: 'e2', label: 'First Home', description: 'Should not own a pucca house', field: 'firstHome', operator: 'bool', value: true },
      { id: 'e3', label: 'Female Ownership', description: 'Preferably female ownership', field: 'gender', operator: 'in', value: ['female', 'any'] },
    ],
    eligibilitySummary: 'EWS/LIG families with income up to ₹6 lakh/year, without a pucca house. Interest subsidy up to ₹2.67 lakh.',
    requiredDocuments: ['Aadhaar Card', 'Income Certificate', 'Bank account details', 'Property documents', 'Caste Certificate (if applicable)', 'Photographs'],
    applicationProcess: [
      'Visit pmaymis.gov.in (urban) or pmayg.nic.in (gramin)',
      'Register with Aadhaar number',
      'Fill application with income and family details',
      'Upload required documents',
      'Check eligibility for subsidy and track application',
    ],
    officialSource: 'PMAY Portal',
    sourceUrl: 'https://pmaymis.gov.in',
    lastVerified: '2025-01-18',
    availability: 'national',
    benefits: 'Interest subsidy up to ₹2.67 lakh on home loans. Grant up to ₹1.2 lakh for EWS construction.',
    tags: ['housing', 'home loan', 'subsidy', 'welfare'],
  },
  {
    id: 'nrega',
    name: 'Mahatma Gandhi NREGA (MGNREGA)',
    nameHi: 'महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम',
    category: 'employment',
    department: 'Ministry of Rural Development',
    shortDescription: '100 days of guaranteed wage employment per year to rural households.',
    description:
      'MGNREGA guarantees 100 days of wage employment per year to every rural household whose adult members volunteer to do unskilled manual work. It aims to enhance livelihood security in rural areas.',
    eligibility: [
      { id: 'e1', label: 'Location', description: 'Must be a rural household', field: 'location', operator: 'eq', value: 'rural' },
      { id: 'e2', label: 'Adult', description: 'Adult member willing to do unskilled manual work', field: 'age', operator: 'gte', value: 18 },
    ],
    eligibilitySummary: 'All rural households with adult members willing to do unskilled manual work. 100 days guaranteed employment.',
    requiredDocuments: ['Aadhaar Card', 'Residence proof', 'Photograph', 'Bank account details (for wage payment)'],
    applicationProcess: [
      'Visit your Gram Panchayat office',
      'Fill the MGNREGA job card application form',
      'Submit with photographs and residence proof',
      'Job card is issued within 30 days',
      'Demand work — employment must be provided within 15 days',
    ],
    officialSource: 'MGNREGA Portal',
    sourceUrl: 'https://nrega.nic.in',
    lastVerified: '2025-01-08',
    availability: 'national',
    benefits: '100 days of guaranteed wage employment per year at notified minimum wage',
    tags: ['employment', 'rural', 'wages', 'guaranteed work'],
  },
  {
    id: 'pmkvy',
    name: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)',
    nameHi: 'प्रधानमंत्री कौशल विकास योजना',
    category: 'employment',
    department: 'Ministry of Skill Development and Entrepreneurship',
    shortDescription: 'Free skill training and certification for youth.',
    description:
      'PMKVY provides free short-term skill training to youth across India. Trainees receive a certificate on successful completion and assessment, along with placement support.',
    eligibility: [
      { id: 'e1', label: 'Age', description: '15 to 45 years', field: 'age', operator: 'lte', value: 45 },
      { id: 'e2', label: 'Education', description: 'No formal education required for most courses', field: 'education', operator: 'gte', value: 0 },
      { id: 'e3', label: 'Nationality', description: 'Indian citizen with Aadhaar', field: 'nationality', operator: 'eq', value: 'indian' },
    ],
    eligibilitySummary: 'Indian youth aged 15-45. Free training, certification, and placement support.',
    requiredDocuments: ['Aadhaar Card', 'Educational certificates (if any)', 'Bank account details', 'Photograph'],
    applicationProcess: [
      'Visit pmkvyofficial.org or nearest PMKVY training center',
      'Register with Aadhaar number',
      'Choose a skill course from available options',
      'Attend training (1-6 months depending on course)',
      'Get certified after assessment + placement support',
    ],
    officialSource: 'PMKVY Portal',
    sourceUrl: 'https://www.pmkvyofficial.org',
    lastVerified: '2025-01-25',
    availability: 'national',
    benefits: 'Free skill training + certification + average ₹8,000 stipend (for special components) + placement support',
    tags: ['skill', 'training', 'youth', 'employment', 'free'],
  },
  {
    id: 'beti-bachao',
    name: 'Beti Bachao Beti Padhao (BBBP)',
    nameHi: 'बेटी बचाओ बेटी पढ़ाओ',
    category: 'welfare',
    department: 'Ministry of Women and Child Development',
    shortDescription: 'Education and welfare support for the girl child.',
    description:
      'BBBP aims to address declining Child Sex Ratio and promote education and empowerment of the girl child. It includes awareness campaigns, Sukanya Samriddhi Yojana promotion, and enforcement of PC&PNDT Act.',
    eligibility: [
      { id: 'e1', label: 'Gender', description: 'Girl child below 10 years', field: 'gender', operator: 'eq', value: 'female' },
      { id: 'e2', label: 'Age', description: 'Girl child up to 10 years for Sukanya account', field: 'age', operator: 'lte', value: 10 },
    ],
    eligibilitySummary: 'Families with girl children. Sukanya Samriddhi account can be opened for girls up to age 10.',
    requiredDocuments: ['Girl child\'s birth certificate', 'Aadhaar Card', 'Parent\'s ID proof', 'Photograph', 'Address proof'],
    applicationProcess: [
      'Visit any post office or authorized bank',
      'Open a Sukanya Samriddhi Account in the girl child\'s name',
      'Deposit minimum ₹250 to maximum ₹1.5 lakh per year',
      'Enjoy highest interest rate among small savings schemes (8.2%)',
      'Account matures after 21 years or on marriage after 18',
    ],
    officialSource: 'BBBP Portal',
    sourceUrl: 'https://wcd.nic.in/bbbp',
    lastVerified: '2025-01-30',
    availability: 'national',
    benefits: 'Sukanya Samriddhi: 8.2% interest, tax-free. Education and empowerment programs for girls.',
    tags: ['women', 'girl child', 'education', 'welfare', 'savings'],
  },
  {
    id: 'stand-up-india',
    name: 'Stand-Up India',
    nameHi: 'स्टैंड-अप इंडिया',
    category: 'finance',
    department: 'Ministry of Finance',
    shortDescription: 'Bank loans ₹10 lakh-₹1 crore for SC/ST and women entrepreneurs.',
    description:
      'Stand-Up India facilitates bank loans between ₹10 lakh and ₹1 crore to SC/ST and women entrepreneurs for setting up greenfield enterprises in manufacturing, services, or trading sector.',
    eligibility: [
      { id: 'e1', label: 'Category', description: 'SC, ST, or Women entrepreneurs', field: 'category', operator: 'in', value: ['SC', 'ST', 'women'] },
      { id: 'e2', label: 'First-time', description: 'First-time borrower for greenfield enterprise', field: 'firstTime', operator: 'bool', value: true },
      { id: 'e3', label: 'Age', description: '18 years and above', field: 'age', operator: 'gte', value: 18 },
    ],
    eligibilitySummary: 'SC/ST and women entrepreneurs, 18+, setting up a first greenfield enterprise. Loan: ₹10L-₹1Cr.',
    requiredDocuments: ['Aadhaar Card', 'Caste Certificate (for SC/ST)', 'Business plan/project report', 'Bank account details', 'PAN Card', 'Address proof'],
    applicationProcess: [
      'Visit standupmitra.in or your nearest bank branch',
      'Prepare a business plan/project report',
      'Apply through the portal or directly at the bank',
      'Bank evaluates and sanctions the loan',
      'Loan is disbursed with 7-year repayment period',
    ],
    officialSource: 'Stand-Up India Portal',
    sourceUrl: 'https://www.standupmitra.in',
    lastVerified: '2025-02-05',
    availability: 'national',
    benefits: 'Bank loan ₹10 lakh to ₹1 crore for greenfield enterprise. 7-year repayment. Refinance option.',
    tags: ['entrepreneur', 'women', 'sc', 'st', 'business loan', 'finance'],
  },
  {
    id: 'pm-svanidhi',
    name: 'PM SVANidhi (Street Vendors)',
    nameHi: 'प्रधानमंत्री स्वनिधि (स्ट्रीट वेंडर्स)',
    category: 'finance',
    department: 'Ministry of Housing and Urban Affairs',
    shortDescription: 'Working capital loan up to ₹50,000 for street vendors.',
    description:
      'PM SVANidhi provides affordable working capital loans to street vendors to resume their businesses post-pandemic and build a credit history for larger loans in the future.',
    eligibility: [
      { id: 'e1', label: 'Vendor', description: 'Must be a street vendor', field: 'occupation', operator: 'eq', value: 'vendor' },
      { id: 'e2', label: 'Location', description: 'Urban/peri-urban areas', field: 'location', operator: 'in', value: ['urban', 'peri-urban'] },
      { id: 'e3', label: 'Certificate', description: 'Vending certificate or ID from ULB', field: 'vendingCert', operator: 'bool', value: true },
    ],
    eligibilitySummary: 'Street vendors in urban areas with vending certificate. Loan up to ₹50,000 at 7% interest subsidy.',
    requiredDocuments: ['Aadhaar Card', 'Vending Certificate or Letter of Recommendation from ULB', 'Bank account details', 'Mobile number'],
    applicationProcess: [
      'Visit pmsvanidhi.mohua.gov.in or nearest CSC',
      'Register with mobile number and Aadhaar',
      'Upload vending certificate or get LoR from ULB',
      'Apply for loan (₹10,000 initial, up to ₹50,000)',
      'Loan disbursed to bank account within 30 days',
    ],
    officialSource: 'PM SVANidhi Portal',
    sourceUrl: 'https://pmsvanidhi.mohua.gov.in',
    lastVerified: '2025-01-22',
    availability: 'national',
    benefits: 'Working capital loan up to ₹50,000. 7% interest subsidy. Cashback up to ₹1,200 on digital transactions.',
    tags: ['vendor', 'street vendor', 'loan', 'urban', 'finance'],
  },
  {
    id: 'apmc-farmer',
    name: 'Soil Health Card Scheme',
    nameHi: 'मृदा स्वास्थ्य कार्ड योजना',
    category: 'agriculture',
    department: 'Ministry of Agriculture and Farmers Welfare',
    shortDescription: 'Free soil testing and crop-specific fertilizer recommendations.',
    description:
      'The Soil Health Card Scheme provides farmers with a soil health card every 2 years, containing test results of their farm soil and crop-specific fertilizer recommendations to improve productivity and reduce input costs.',
    eligibility: [
      { id: 'e1', label: 'Farmer', description: 'All farmers with cultivable land', field: 'isFarmer', operator: 'bool', value: true },
      { id: 'e2', label: 'Land', description: 'Must have cultivable land', field: 'land', operator: 'bool', value: true },
    ],
    eligibilitySummary: 'All farmers with cultivable land. Free soil testing every 2 years with fertilizer recommendations.',
    requiredDocuments: ['Aadhaar Card', 'Land ownership documents', 'Bank account details (optional)'],
    applicationProcess: [
      'Visit your nearest soil testing lab or Krishi Vigyan Kendra',
      'Submit land details and Aadhaar',
      'Collect soil sample as per instructions',
      'Submit sample for testing',
      'Receive Soil Health Card with recommendations within 2-4 weeks',
    ],
    officialSource: 'Soil Health Card Portal',
    sourceUrl: 'https://soilhealth.dac.gov.in',
    lastVerified: '2025-01-14',
    availability: 'national',
    benefits: 'Free soil testing + crop-specific fertilizer recommendations. Reduces input cost by 8-10%.',
    tags: ['farmer', 'agriculture', 'soil', 'free', 'fertilizer'],
  },
  {
    id: 'widow-pension',
    name: 'Indira Gandhi National Widow Pension Scheme (IGNWPS)',
    nameHi: 'इंदिरा गांधी राष्ट्रीय विधवा पेंशन योजना',
    category: 'pension',
    department: 'Ministry of Rural Development',
    shortDescription: 'Monthly pension for BPL widows aged 40-79.',
    description:
      'IGNWPS provides a monthly pension of ₹300 to widows aged 40-79 years belonging to BPL households. States may add additional amounts. After age 80, the beneficiary shifts to IGNOAPS.',
    eligibility: [
      { id: 'e1', label: 'Marital Status', description: 'Must be a widow', field: 'maritalStatus', operator: 'eq', value: 'widowed' },
      { id: 'e2', label: 'Age', description: '40 to 79 years', field: 'age', operator: 'gte', value: 40 },
      { id: 'e3', label: 'BPL', description: 'Must belong to a BPL household', field: 'bpl', operator: 'bool', value: true },
    ],
    eligibilitySummary: 'BPL widows aged 40-79. ₹300/month from central + state top-up.',
    requiredDocuments: ['Aadhaar Card', 'Death certificate of husband', 'Age proof', 'BPL Certificate', 'Bank passbook', 'Residence proof'],
    applicationProcess: [
      'Visit your Gram Panchayat / Municipality office',
      'Fill the IGNWPS application form',
      'Attach death certificate, age proof, BPL certificate, bank details',
      'Submit to the concerned officer',
      'Pension is credited directly to bank account',
    ],
    officialSource: 'NSAP Portal',
    sourceUrl: 'https://nsap.nic.in',
    lastVerified: '2025-01-06',
    availability: 'national',
    benefits: '₹300/month (central) + state top-up. Shifts to IGNOAPS (₹500) after age 80.',
    tags: ['pension', 'widow', 'welfare', 'bpl', 'women'],
  },
];

export const DEMO_PERSONAS: DemoPersona[] = [
  {
    id: 'student-bihar',
    name: 'Aarav Kumar',
    role: 'Engineering Student',
    avatar: '🎓',
    state: 'Bihar',
    description: '20-year-old engineering student from Patna, Bihar. Family income ₹2 lakh/year. Looking for scholarships and education support.',
    profile: {
      age: 20,
      state: 'Bihar',
      district: 'Patna',
      occupation: 'Student',
      isStudent: true,
      incomeRange: '0-3 lakh',
      gender: 'male',
      location: 'urban',
      employmentStatus: 'student',
    },
    suggestedQuery: 'I am an engineering student from Bihar. My family income is ₹2 lakh per year. Which scholarships can I apply for?',
    journey: ['Discovered Post Matric Scholarship', 'Checked eligibility for NSP Merit Scholarship', 'Prepared income certificate', 'Started application'],
    color: 'from-blue-500 to-indigo-600',
  },
  {
    id: 'farmer-up',
    name: 'Ramesh Singh',
    role: 'Farmer',
    avatar: '🌾',
    state: 'Uttar Pradesh',
    description: '45-year-old farmer from Varanasi, UP. Owns 2 acres of land. Looking for agricultural schemes, subsidies, and crop insurance.',
    profile: {
      age: 45,
      state: 'Uttar Pradesh',
      district: 'Varanasi',
      occupation: 'Farmer',
      isFarmer: true,
      incomeRange: '1-3 lakh',
      gender: 'male',
      location: 'rural',
      employmentStatus: 'self-employed',
    },
    suggestedQuery: 'I am a farmer with 2 acres of land in UP. What government schemes and subsidies can help me?',
    journey: ['Discovered PM-KISAN', 'Applied for crop insurance (PMFBY)', 'Got Soil Health Card', 'Received ₹6,000 PM-KISAN benefit'],
    color: 'from-green-500 to-emerald-600',
  },
  {
    id: 'citizen-delhi',
    name: 'Priya Sharma',
    role: 'Working Professional',
    avatar: '👩',
    state: 'Delhi',
    description: '32-year-old working professional from Delhi. Wants to report a garbage overflow issue in her neighborhood and track civic services.',
    profile: {
      age: 32,
      state: 'Delhi',
      district: 'South Delhi',
      occupation: 'Professional',
      incomeRange: '6-10 lakh',
      gender: 'female',
      location: 'urban',
      employmentStatus: 'employed',
    },
    suggestedQuery: 'There is an overflowing garbage dump near my house for the last five days. How do I report it?',
    journey: ['Reported garbage overflow', 'Complaint assigned to MCD', 'Issue under review', 'Filed escalation after 3 days'],
    color: 'from-orange-500 to-red-500',
  },
];

export const SEED_COMPLAINTS: Complaint[] = [
  {
    id: 'c1',
    ticketId: 'SB-2025-001',
    title: 'Overflowing garbage dump near residential area',
    description: 'A large garbage dump has been overflowing near Block C, Saket for the past 5 days. It is causing foul smell and attracting mosquitoes. Residents are facing health issues.',
    category: 'garbage',
    urgency: 'high',
    status: 'in_progress',
    department: 'Municipal Corporation (MCD)',
    location: { lat: 28.5245, lng: 77.2066, address: 'Block C, Saket, South Delhi', area: 'Saket' },
    imageUrl: 'https://images.pexels.com/photos/2662086/pexels-photo-2662086.jpeg?auto=compress&cs=tinysrgb&w=800',
    createdAt: '2025-07-01T10:30:00Z',
    updatedAt: '2025-07-05T14:00:00Z',
    isMock: true,
    assignedTo: 'MCD Ward 12 - Sanitation Team',
    timeline: [
      { status: 'submitted', timestamp: '2025-07-01T10:30:00Z', note: 'Complaint submitted via Smart Bharat AI', by: 'Citizen' },
      { status: 'under_review', timestamp: '2025-07-02T09:15:00Z', note: 'Complaint received and assigned to MCD Ward 12', by: 'MCD Control Room' },
      { status: 'in_progress', timestamp: '2025-07-05T14:00:00Z', note: 'Sanitation team dispatched for assessment. Cleanup scheduled.', by: 'MCD Ward 12' },
    ],
  },
  {
    id: 'c2',
    ticketId: 'SB-2025-002',
    title: 'Large pothole on main road causing accidents',
    description: 'A large pothole has developed on the main road near the bus stop. Two-wheeler riders have fallen and been injured. Needs urgent repair.',
    category: 'potholes',
    urgency: 'critical',
    status: 'escalated',
    department: 'Public Works Department (PWD)',
    location: { lat: 28.6139, lng: 77.209, address: 'Near Bus Stop, Connaught Place, New Delhi', area: 'Connaught Place' },
    imageUrl: 'https://images.pexels.com/photos/2531709/pexels-photo-2531709.jpeg?auto=compress&cs=tinysrgb&w=800',
    createdAt: '2025-06-20T08:00:00Z',
    updatedAt: '2025-07-03T11:00:00Z',
    isMock: true,
    assignedTo: 'PWD Road Maintenance Division 3',
    timeline: [
      { status: 'submitted', timestamp: '2025-06-20T08:00:00Z', note: 'Complaint submitted with photo evidence', by: 'Citizen' },
      { status: 'under_review', timestamp: '2025-06-21T10:00:00Z', note: 'PWD team assigned for inspection', by: 'PWD Control' },
      { status: 'in_progress', timestamp: '2025-06-25T09:00:00Z', note: 'Inspection complete. Repair work scheduled.', by: 'PWD Division 3' },
      { status: 'escalated', timestamp: '2025-07-03T11:00:00Z', note: 'No action taken in 10 days. Escalated to Chief Engineer.', by: 'Citizen (via Smart Bharat)' },
    ],
  },
  {
    id: 'c3',
    ticketId: 'SB-2025-003',
    title: 'Broken streetlight in dark alley',
    description: 'Streetlight has been broken for 2 weeks in the alley behind our society. It is unsafe for women and children at night.',
    category: 'streetlight',
    urgency: 'medium',
    status: 'resolved',
    department: 'Delhi Electricity Board (DESU)',
    location: { lat: 28.5355, lng: 77.2391, address: 'Alley behind Green Park Society', area: 'Green Park' },
    createdAt: '2025-06-10T19:00:00Z',
    updatedAt: '2025-06-18T16:00:00Z',
    isMock: true,
    assignedTo: 'DESU Maintenance Team',
    timeline: [
      { status: 'submitted', timestamp: '2025-06-10T19:00:00Z', note: 'Complaint submitted via Smart Bharat', by: 'Citizen' },
      { status: 'under_review', timestamp: '2025-06-11T08:00:00Z', note: 'Assigned to DESU maintenance', by: 'DESU Control' },
      { status: 'in_progress', timestamp: '2025-06-15T10:00:00Z', note: 'Technician dispatched for repair', by: 'DESU Team' },
      { status: 'resolved', timestamp: '2025-06-18T16:00:00Z', note: 'Streetlight replaced and tested. Issue resolved.', by: 'DESU Team' },
    ],
  },
  {
    id: 'c4',
    ticketId: 'SB-2025-004',
    title: 'Water leakage from main pipeline',
    description: 'Continuous water leakage from the main pipeline on MG Road. Wastage of water and road damage.',
    category: 'water',
    urgency: 'high',
    status: 'under_review',
    department: 'Delhi Jal Board (DJB)',
    location: { lat: 28.4745, lng: 77.0801, address: 'MG Road, near Metro Station', area: 'MG Road' },
    createdAt: '2025-07-03T07:00:00Z',
    updatedAt: '2025-07-04T10:00:00Z',
    isMock: true,
    assignedTo: 'DJB South Zone',
    timeline: [
      { status: 'submitted', timestamp: '2025-07-03T07:00:00Z', note: 'Complaint submitted with location', by: 'Citizen' },
      { status: 'under_review', timestamp: '2025-07-04T10:00:00Z', note: 'Assigned to DJB South Zone for inspection', by: 'DJB Control' },
    ],
  },
  {
    id: 'c5',
    ticketId: 'SB-2025-005',
    title: 'Drainage overflow during rain',
    description: 'Drainage is overflowing onto the street every time it rains. Sewage water entering homes. Health hazard.',
    category: 'drainage',
    urgency: 'high',
    status: 'in_progress',
    department: 'Municipal Corporation (MCD)',
    location: { lat: 28.7041, lng: 77.1025, address: 'Sector 7, Rohini', area: 'Rohini' },
    createdAt: '2025-06-28T15:00:00Z',
    updatedAt: '2025-07-02T12:00:00Z',
    isMock: true,
    assignedTo: 'MCD North Zone - Drainage',
    timeline: [
      { status: 'submitted', timestamp: '2025-06-28T15:00:00Z', note: 'Complaint submitted', by: 'Citizen' },
      { status: 'under_review', timestamp: '2025-06-29T09:00:00Z', note: 'Assigned to MCD North Zone', by: 'MCD Control' },
      { status: 'in_progress', timestamp: '2025-07-02T12:00:00Z', note: 'Drainage cleaning in progress. Jet pump deployed.', by: 'MCD North' },
    ],
  },
  {
    id: 'c6',
    ticketId: 'SB-2025-006',
    title: 'Illegal dumping of construction waste',
    description: 'Construction debris being dumped illegally on empty plot near school. Children at risk.',
    category: 'dumping',
    urgency: 'medium',
    status: 'submitted',
    department: 'Municipal Corporation (MCD)',
    location: { lat: 28.5900, lng: 77.3000, address: 'Near Govt School, Mayur Vihar', area: 'Mayur Vihar' },
    createdAt: '2025-07-05T11:00:00Z',
    updatedAt: '2025-07-05T11:00:00Z',
    isMock: true,
    timeline: [
      { status: 'submitted', timestamp: '2025-07-05T11:00:00Z', note: 'Complaint submitted with photo evidence', by: 'Citizen' },
    ],
  },
];

export const SEED_JOURNEY: CivicJourneyEvent[] = [
  {
    id: 'j1',
    type: 'ai_consultation',
    title: 'Asked Bharat AI about scholarships',
    description: 'AI recommended 3 schemes based on your profile: student, Bihar, ₹2L income.',
    timestamp: '2025-07-06T09:00:00Z',
    icon: 'message',
    relatedType: 'scheme',
  },
  {
    id: 'j2',
    type: 'scheme_discovered',
    title: 'Discovered Post Matric Scholarship (SC/ST)',
    description: 'Found via AI recommendation. 85% eligibility match.',
    timestamp: '2025-07-06T09:05:00Z',
    icon: 'search',
    relatedId: 'pmsss',
    relatedType: 'scheme',
  },
  {
    id: 'j3',
    type: 'eligibility_checked',
    title: 'Eligibility checked for NSP Merit Scholarship',
    description: 'AI assessed: 2 of 3 conditions met. Income certificate needed.',
    timestamp: '2025-07-06T09:20:00Z',
    icon: 'check',
    relatedId: 'nsp-merit',
    relatedType: 'scheme',
  },
  {
    id: 'j4',
    type: 'documents_prepared',
    title: 'Document readiness: 67%',
    description: 'Income certificate and mark sheet verified. Caste certificate pending.',
    timestamp: '2025-07-06T10:00:00Z',
    icon: 'file',
    relatedType: 'document',
  },
  {
    id: 'j5',
    type: 'complaint_submitted',
    title: 'Complaint filed: Garbage overflow',
    description: 'Ticket SB-2025-001 created. Assigned to MCD. AI-generated complaint.',
    timestamp: '2025-07-01T10:30:00Z',
    icon: 'alert',
    relatedId: 'c1',
    relatedType: 'complaint',
  },
  {
    id: 'j6',
    type: 'complaint_updated',
    title: 'Complaint status: In Progress',
    description: 'MCD sanitation team dispatched for assessment.',
    timestamp: '2025-07-05T14:00:00Z',
    icon: 'clock',
    relatedId: 'c1',
    relatedType: 'complaint',
  },
];

export const DASHBOARD_STATS: DashboardStats = {
  schemesDiscovered: 12,
  applicationsPrepared: 3,
  documentsCompleted: 8,
  complaintsSubmitted: 4,
  complaintsResolved: 2,
  avgResolutionTime: '6.5 days',
  civicImpactScore: 78,
};

export const ADMIN_METRICS: AdminMetrics = {
  totalComplaints: 248,
  byCategory: [
    { category: 'garbage', count: 78 },
    { category: 'potholes', count: 52 },
    { category: 'streetlight', count: 34 },
    { category: 'water', count: 28 },
    { category: 'drainage', count: 22 },
    { category: 'road', count: 18 },
    { category: 'safety', count: 10 },
    { category: 'dumping', count: 6 },
  ],
  byStatus: [
    { status: 'resolved', count: 142 },
    { status: 'in_progress', count: 58 },
    { status: 'under_review', count: 32 },
    { status: 'submitted', count: 12 },
    { status: 'escalated', count: 4 },
  ],
  resolutionRate: 57.3,
  departmentWorkload: [
    { department: 'MCD', count: 112, avgDays: 5.2 },
    { department: 'PWD', count: 48, avgDays: 8.1 },
    { department: 'DJB', count: 36, avgDays: 4.5 },
    { department: 'DESU', count: 28, avgDays: 3.8 },
    { department: 'Police', count: 24, avgDays: 6.0 },
  ],
  emergingIssues: [
    { title: 'Garbage overflow in South Delhi', trend: 'up', count: 23 },
    { title: 'Potholes after monsoon rain', trend: 'up', count: 18 },
    { title: 'Streetlight failures in Rohini', trend: 'stable', count: 12 },
    { title: 'Water leakage on MG Road', trend: 'down', count: 8 },
  ],
  civicPulse:
    'Garbage management issues are rising sharply in South Delhi (up 40% this week), driven by monsoon overflow. Pothole complaints have spiked post-rainfall across central Delhi. MCD sanitation workload is at 85% capacity. Recommend proactive drain cleaning in flood-prone areas before next rainfall.',
  weeklyTrend: [
    { week: 'W1', complaints: 28, resolved: 18 },
    { week: 'W2', complaints: 35, resolved: 22 },
    { week: 'W3', complaints: 42, resolved: 30 },
    { week: 'W4', complaints: 38, resolved: 28 },
    { week: 'W5', complaints: 45, resolved: 32 },
    { week: 'W6', complaints: 60, resolved: 12 },
  ],
};

export const CATEGORY_LABELS: Record<string, string> = {
  education: 'Education',
  agriculture: 'Agriculture',
  pension: 'Pension',
  welfare: 'Welfare',
  employment: 'Employment',
  health: 'Health',
  housing: 'Housing',
  finance: 'Finance',
};

export const COMPLAINT_CATEGORY_LABELS: Record<string, string> = {
  garbage: 'Garbage',
  potholes: 'Potholes',
  streetlight: 'Streetlight',
  water: 'Water',
  drainage: 'Drainage',
  road: 'Road Damage',
  safety: 'Public Safety',
  dumping: 'Illegal Dumping',
  other: 'Other',
};

export const STATUS_LABELS: Record<string, string> = {
  submitted: 'Submitted',
  under_review: 'Under Review',
  in_progress: 'In Progress',
  resolved: 'Resolved',
  escalated: 'Escalated',
};
